"""Write src/world-dots.js: the land of the world as a grid of dots.

The directory's map draws the continents as dots and the ISTN's countries as
lights on top. The dots are computed once, here, from an equirectangular land
mask — by default the one macOS ships in GeoKit — and stored as runs per row,
a few kilobytes that the app turns into one SVG path. No map service is called
from the phones, and the map works offline.

    python3 scripts/build_world_map.py [mask.png]
"""

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MASK = '/System/Library/PrivateFrameworks/GeoKit.framework/Versions/A/Resources/worldmap@2x.png'
OUTPUT = ROOT / 'src' / 'world-dots.js'

STEP = 3.6          # degrees per dot, in both directions: 100 columns
NORTH, SOUTH = 80.0, -56.8   # Greenland's coast to Cape Horn; Antarctica left out
LAND = 0.3          # share of a cell that must be land for it to get a dot


def main() -> None:
    source = sys.argv[1] if len(sys.argv) > 1 else MASK
    image = Image.open(source).convert('RGBA')
    width, height = image.size
    alpha = image.getchannel('A').load()
    pixels = image.convert('L').load()

    def is_land(x, y):
        # The mask is black land on a transparent (or white) sea.
        return alpha[x, y] > 128 and pixels[x, y] < 128

    cols = round(360 / STEP)
    rows = round((NORTH - SOUTH) / STEP)
    runs = []
    dots = 0
    for row in range(rows):
        lat_top = NORTH - row * STEP
        y0 = int((90 - lat_top) / 180 * height)
        y1 = max(y0 + 1, int((90 - (lat_top - STEP)) / 180 * height))
        line, start = [], None
        for col in range(cols + 1):
            land = False
            if col < cols:
                x0 = int(col * STEP / 360 * width)
                x1 = max(x0 + 1, int((col + 1) * STEP / 360 * width))
                cells = [(x, y) for x in range(x0, x1) for y in range(y0, min(y1, height))]
                land = sum(is_land(x, y) for x, y in cells) / len(cells) >= LAND
            if land and start is None:
                start = col
            elif not land and start is not None:
                line.append(f'{start}.{col - start}')
                dots += col - start
                start = None
        runs.append(' '.join(line))

    OUTPUT.write_text(
        '// Generated by scripts/build_world_map.py — do not edit by hand.\n'
        '// The land of the world on a grid of dots, equirectangular: each row lists\n'
        '// its runs of land as "first.length", in columns.\n'
        f'export const WORLD_DOTS = {{ step: {STEP}, north: {NORTH}, cols: {cols}, rows: {rows}, runs: {runs!r} }};\n'
        .replace("'", '"').replace('[', '[\n  ').replace('", "', '",\n  "').replace('"]', '"\n]'),
        encoding='utf-8')
    print(f'{dots} pontos em {cols}x{rows} -> {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size // 1024} KB)')


if __name__ == '__main__':
    main()
