"""Turn the operational JSON files into supabase/seed.sql.

The church records stay exactly as supplied — including their needs_review
status. Nothing is corrected or merged here; that is the admin panel's job.

    python3 scripts/generate_seed.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data'
OUTPUT = ROOT / 'supabase' / 'seed.sql'


def sql(value) -> str:
    if value is None or value == '':
        return 'null'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    physical = json.loads((DATA / 'church-service-source-records.json').read_text('utf-8'))
    online = json.loads((DATA / 'online-communities-source-records.json').read_text('utf-8'))
    live = json.loads((DATA / 'live-config.json').read_text('utf-8'))

    lines = [
        '-- Generated by scripts/generate_seed.py — do not edit by hand.',
        '-- Re-running is safe: rows are matched on record_id.',
        '',
        'begin;',
        '',
        '-- ------------------------------------------------------ churches --',
    ]

    columns = ('record_id', 'modality', 'country_code', 'country', 'region', 'locality',
               'service_day', 'service_time_local', 'leader_name', 'leader_phone',
               'note', 'source', 'verification_status')

    rows = []
    for record in physical:
        rows.append({
            'record_id': record.get('record_id'),
            'modality': 'physical',
            'country_code': record.get('country_code'),
            'country': None,
            'region': record.get('region'),
            'locality': record.get('locality'),
            'service_day': record.get('service_day'),
            'service_time_local': record.get('service_time_local'),
            'leader_name': record.get('leader_name'),
            'leader_phone': record.get('leader_phone'),
            'note': None,
            'source': record.get('source'),
            'verification_status': record.get('verification_status', 'needs_review'),
        })
    for index, record in enumerate(online, start=1):
        rows.append({
            'record_id': f'online_record_{index:03d}',
            'modality': 'online',
            'country_code': None,
            'country': record.get('country'),
            'region': None,
            'locality': None,
            'service_day': None,
            'service_time_local': None,
            'leader_name': record.get('contact'),
            'leader_phone': record.get('phone'),
            'note': record.get('note'),
            'source': None,
            'verification_status': record.get('verification_status', 'needs_review'),
        })

    lines.append(f'insert into public.churches ({", ".join(columns)}) values')
    values = [f'  ({", ".join(sql(row[column]) for column in columns)})' for row in rows]
    lines.append(',\n'.join(values))
    lines.append('on conflict (record_id) do nothing;')
    lines.append('')
    lines.append('-- --------------------------------------------------- live config --')
    zoom = live.get('zoom', {})
    lines.append(
        'insert into public.live_config '
        '(singleton, title, subtitle, time_zone, zoom_url, zoom_meeting_id, zoom_passcode, '
        'youtube_url, note, duration_minutes, schedule) values\n'
        f'  (true, {sql(live.get("title"))}, {sql(live.get("subtitle"))}, {sql(live.get("timeZone"))}, '
        f'{sql(zoom.get("url"))}, {sql(zoom.get("meetingId"))}, {sql(zoom.get("passcode"))}, '
        f'{sql(live.get("youtubeUrl"))}, {sql(live.get("note"))}, {live.get("durationMinutes", 120)}, '
        f'{sql(json.dumps(live.get("schedule", []), ensure_ascii=False))}::jsonb)\n'
        'on conflict (singleton) do nothing;'
    )
    lines.append('')
    lines.append('commit;')

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(rows)} congregações e 1 configuração de lives -> {OUTPUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
