-- {{NAME}}: the directory, from the team's general list of services.
--
-- Generated by scripts/import_churches.py, together with data/igrejas.json, so
-- the database and the app's own copy never disagree. Do not edit by hand:
-- change the workbook or the script and generate a new migration.
-- data/importacao-igrejas.md lists every decision taken on the way.
--
-- In one transaction:
--  1. each place gains its seat (world or national), the other people
--     responsible for it, and the ids it had before, so old links still open;
--  2. the records that were one place announced twice (Kifica on Saturday,
--     Kifica on Sunday) become one, and everything that pointed at the second
--     — servants, a local editor, a member's "A minha ISTN", announcements —
--     is moved onto the first before it goes;
--  3. every place takes the list's data, and its service times are replaced
--     by the list's.
--
-- It runs once. The import is recorded in data_imports, and running the file
-- again changes nothing: an edit made in the panel afterwards is never undone
-- by a second run.

begin;

-- ----------------------------------------------------------------- colunas --

alter table public.churches
  add column if not exists seat              text,
  add column if not exists other_leaders     jsonb  not null default '[]'::jsonb,
  add column if not exists former_record_ids text[] not null default '{}';

do $$ begin
  alter table public.churches
    add constraint churches_seat_known check (seat is null or seat in ('mundial', 'nacional'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.churches
    add constraint churches_other_leaders_list check (jsonb_typeof(other_leaders) = 'array');
exception when duplicate_object then null; end $$;

-- One world seat, and at most one national seat in each country.
create unique index if not exists churches_one_world_seat
  on public.churches ((seat)) where seat = 'mundial';
create unique index if not exists churches_one_national_seat
  on public.churches ((coalesce(country_code, country))) where seat = 'nacional';

create index if not exists churches_former_record_ids_idx
  on public.churches using gin (former_record_ids);

comment on column public.churches.seat is
  'mundial ou nacional. Só a equipa central muda, com set_church_seat.';
comment on column public.churches.other_leaders is
  'Outros responsáveis além de leader_name, [{name, phone}], como os anúncios os publicam.';
comment on column public.churches.former_record_ids is
  'Identificadores que este lugar teve antes, para que links e «A minha ISTN» antigos continuem a abri-lo.';

-- ------------------------------------------------------------------- sede --

-- The seat says something about the whole ISTN, not about one place, so a
-- local editor cannot give it to their own church, even through the API.
-- Without a signed-in user this is the SQL editor or a migration.
create or replace function public.protect_church_seat()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or public.is_central() then
    return new;
  end if;
  new.seat := old.seat;
  return new;
end $$;

drop trigger if exists churches_protect_seat on public.churches;
create trigger churches_protect_seat
  before update on public.churches
  for each row execute function public.protect_church_seat();

-- Giving a place a seat takes it from whoever held it, in the same
-- transaction: the unique indexes would otherwise refuse the second place
-- while the first still has it.
create or replace function public.set_church_seat(p_church uuid, p_seat text)
returns void language plpgsql security invoker set search_path = public as $$
declare
  target public.churches;
begin
  if not public.is_central() then
    raise exception 'Só a equipa central define as sedes.';
  end if;
  if p_seat is not null and p_seat not in ('mundial', 'nacional') then
    raise exception 'Sede desconhecida: %.', p_seat;
  end if;
  select * into target from public.churches where id = p_church;
  if not found then
    raise exception 'Igreja não encontrada.';
  end if;
  if p_seat = 'mundial' then
    update public.churches set seat = null where seat = 'mundial' and id <> p_church;
  elsif p_seat = 'nacional' then
    update public.churches set seat = null
     where seat = 'nacional' and id <> p_church
       and coalesce(country_code, country) = coalesce(target.country_code, target.country);
  end if;
  update public.churches set seat = p_seat where id = p_church;
end $$;

revoke all on function public.set_church_seat(uuid, text) from public, anon;
grant execute on function public.set_church_seat(uuid, text) to authenticated;

-- ---------------------------------------------------- juntar dois registos --

-- p_other is the same place as p_keep: everything that points at p_other
-- moves to p_keep, what the team filled in on p_other is kept where p_keep has
-- nothing, and p_other goes. Only the SQL editor can call it.
create or replace function public.merge_church_into(p_keep uuid, p_other uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  other public.churches;
begin
  if p_keep = p_other then
    return;
  end if;
  select * into other from public.churches where id = p_other;
  if not found then
    return;
  end if;

  update public.servos set church_id = p_keep where church_id = p_other;
  update public.admin_profiles set church_id = p_keep where church_id = p_other;
  update public.app_users set home_church_id = p_keep where home_church_id = p_other;
  -- posts.church_id cascades on delete: an announcement left pointing at
  -- p_other would disappear with it.
  update public.posts set church_id = p_keep where church_id = p_other;

  update public.churches c set
    place_type         = coalesce(c.place_type, other.place_type),
    became_church_on   = coalesce(c.became_church_on, other.became_church_on),
    address            = coalesce(c.address, other.address),
    whatsapp_group_url = coalesce(c.whatsapp_group_url, other.whatsapp_group_url),
    photo_url          = coalesce(c.photo_url, other.photo_url),
    note               = coalesce(c.note, other.note),
    -- A confirmation of either record is not thrown away.
    verification_status = case when other.verification_status = 'verified' then 'verified' else c.verification_status end,
    verified_at        = coalesce(c.verified_at, other.verified_at),
    verified_by        = coalesce(c.verified_by, other.verified_by),
    former_record_ids  = array(
      select distinct id from unnest(c.former_record_ids || other.former_record_ids || array[other.record_id]) as id
       where id is not null and id is distinct from c.record_id
       order by id)
  where c.id = p_keep;

  delete from public.churches where id = p_other;
end $$;

revoke all on function public.merge_church_into(uuid, uuid) from public, anon, authenticated;

-- ------------------------------------------------------------ importação --

create table if not exists public.data_imports (
  name       text primary key,
  applied_at timestamptz not null default now()
);
-- No policy: nobody reads it through the API.
alter table public.data_imports enable row level security;

-- The places travel inside this block, as one JSON document, and the whole
-- import is a single statement. A temporary table would be simpler to read,
-- but the Supabase SQL editor runs each statement of a file on its own, and a
-- temporary table does not survive that.
do $import$
declare
  item  record;
  keep  uuid;
  other uuid;
  places constant jsonb := $places${{PLACES}}$places$::jsonb;
begin
  if exists (select 1 from public.data_imports where name = '{{NAME}}') then
    raise notice 'A importação {{NAME}} já foi aplicada: nada a fazer.';
    return;
  end if;

  -- The seats are given place by place below; none is left standing from
  -- before, so no country has two while that runs.
  update public.churches set seat = null where seat is not null;

  for item in
    select place.*
      from jsonb_array_elements(places) with ordinality as listed(value, ord)
      cross join lateral jsonb_to_record(listed.value) as place(
        record_id text, former_record_ids text[], modality text, seat text, country_code text, country text,
        region text, locality text, address text, leader_name text, leader_phone text, other_leaders jsonb,
        source text, services jsonb)
     order by listed.ord
  loop
    -- The record that becomes this place: the one with its new id, if a
    -- previous run created it, or else the first of the ids it had before.
    keep := null;
    select c.id into keep from public.churches c
     where c.record_id = item.record_id or c.record_id = any(item.former_record_ids)
     order by c.record_id = item.record_id desc, array_position(item.former_record_ids, c.record_id)
     limit 1;
    if keep is null then
      insert into public.churches (record_id, modality) values (item.record_id, item.modality)
      returning id into keep;
    end if;

    for other in select c.id from public.churches c
      where c.id <> keep and (c.record_id = item.record_id or c.record_id = any(item.former_record_ids))
    loop
      perform public.merge_church_into(keep, other);
    end loop;

    update public.churches c set
      former_record_ids = array(
        select distinct id from unnest(c.former_record_ids || item.former_record_ids || array[c.record_id]) as id
         where id is not null and id <> item.record_id
         order by id),
      record_id          = item.record_id,
      modality           = item.modality,
      seat               = item.seat,
      country_code       = item.country_code,
      country            = item.country,
      region             = item.region,
      locality           = item.locality,
      -- The list's address when it gives one; otherwise whatever the team wrote.
      address            = coalesce(item.address, c.address),
      leader_name        = item.leader_name,
      leader_phone       = item.leader_phone,
      other_leaders      = item.other_leaders,
      source             = item.source,
      -- Retired by migration 003; cleared so they can never stand in for the
      -- times below.
      service_day        = null,
      service_time_local = null
    where c.id = keep;

    delete from public.church_services where church_id = keep;
    insert into public.church_services (church_id, weekday, start_time, label)
    select keep, (service ->> 'weekday')::smallint, nullif(service ->> 'start_time', '')::time, nullif(service ->> 'label', '')
      from jsonb_array_elements(item.services) as service;
  end loop;

  insert into public.data_imports (name) values ('{{NAME}}');
  raise notice 'Importação {{NAME}}: {{COUNT}} lugares.';
end $import$;

commit;
