-- 20260919160000_diretorio_lista_geral: the directory, from the team's general list of services.
--
-- Generated by scripts/import_churches.py, together with data/igrejas.json, so
-- the database and the app's own copy never disagree. Do not edit by hand:
-- change the workbook or the script and generate a new migration.
-- data/importacao-igrejas.md lists every decision taken on the way.
--
-- In one transaction:
--  1. each place gains its seat (world or national), the other people
--     responsible for it, and the ids it had before, so old links still open;
--  2. the records that were one place announced twice (Kifica on Saturday,
--     Kifica on Sunday) become one, and everything that pointed at the second
--     — servants, a local editor, a member's "A minha ISTN", announcements —
--     is moved onto the first before it goes;
--  3. every place takes the list's data, and its service times are replaced
--     by the list's.
--
-- It runs once. The import is recorded in data_imports, and running the file
-- again changes nothing: an edit made in the panel afterwards is never undone
-- by a second run.

begin;

-- ----------------------------------------------------------------- colunas --

alter table public.churches
  add column if not exists seat              text,
  add column if not exists other_leaders     jsonb  not null default '[]'::jsonb,
  add column if not exists former_record_ids text[] not null default '{}';

do $$ begin
  alter table public.churches
    add constraint churches_seat_known check (seat is null or seat in ('mundial', 'nacional'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.churches
    add constraint churches_other_leaders_list check (jsonb_typeof(other_leaders) = 'array');
exception when duplicate_object then null; end $$;

-- One world seat, and at most one national seat in each country.
create unique index if not exists churches_one_world_seat
  on public.churches ((seat)) where seat = 'mundial';
create unique index if not exists churches_one_national_seat
  on public.churches ((coalesce(country_code, country))) where seat = 'nacional';

create index if not exists churches_former_record_ids_idx
  on public.churches using gin (former_record_ids);

comment on column public.churches.seat is
  'mundial ou nacional. Só a equipa central muda, com set_church_seat.';
comment on column public.churches.other_leaders is
  'Outros responsáveis além de leader_name, [{name, phone}], como os anúncios os publicam.';
comment on column public.churches.former_record_ids is
  'Identificadores que este lugar teve antes, para que links e «A minha ISTN» antigos continuem a abri-lo.';

-- ------------------------------------------------------------------- sede --

-- The seat says something about the whole ISTN, not about one place, so a
-- local editor cannot give it to their own church, even through the API.
-- Without a signed-in user this is the SQL editor or a migration.
create or replace function public.protect_church_seat()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or public.is_central() then
    return new;
  end if;
  new.seat := old.seat;
  return new;
end $$;

drop trigger if exists churches_protect_seat on public.churches;
create trigger churches_protect_seat
  before update on public.churches
  for each row execute function public.protect_church_seat();

-- Giving a place a seat takes it from whoever held it, in the same
-- transaction: the unique indexes would otherwise refuse the second place
-- while the first still has it.
create or replace function public.set_church_seat(p_church uuid, p_seat text)
returns void language plpgsql security invoker set search_path = public as $$
declare
  target public.churches;
begin
  if not public.is_central() then
    raise exception 'Só a equipa central define as sedes.';
  end if;
  if p_seat is not null and p_seat not in ('mundial', 'nacional') then
    raise exception 'Sede desconhecida: %.', p_seat;
  end if;
  select * into target from public.churches where id = p_church;
  if not found then
    raise exception 'Igreja não encontrada.';
  end if;
  if p_seat = 'mundial' then
    update public.churches set seat = null where seat = 'mundial' and id <> p_church;
  elsif p_seat = 'nacional' then
    update public.churches set seat = null
     where seat = 'nacional' and id <> p_church
       and coalesce(country_code, country) = coalesce(target.country_code, target.country);
  end if;
  update public.churches set seat = p_seat where id = p_church;
end $$;

revoke all on function public.set_church_seat(uuid, text) from public, anon;
grant execute on function public.set_church_seat(uuid, text) to authenticated;

-- ---------------------------------------------------- juntar dois registos --

-- p_other is the same place as p_keep: everything that points at p_other
-- moves to p_keep, what the team filled in on p_other is kept where p_keep has
-- nothing, and p_other goes. Only the SQL editor can call it.
create or replace function public.merge_church_into(p_keep uuid, p_other uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  other public.churches;
begin
  if p_keep = p_other then
    return;
  end if;
  select * into other from public.churches where id = p_other;
  if not found then
    return;
  end if;

  update public.servos set church_id = p_keep where church_id = p_other;
  update public.admin_profiles set church_id = p_keep where church_id = p_other;
  update public.app_users set home_church_id = p_keep where home_church_id = p_other;
  -- posts.church_id cascades on delete: an announcement left pointing at
  -- p_other would disappear with it.
  update public.posts set church_id = p_keep where church_id = p_other;

  update public.churches c set
    place_type         = coalesce(c.place_type, other.place_type),
    became_church_on   = coalesce(c.became_church_on, other.became_church_on),
    address            = coalesce(c.address, other.address),
    whatsapp_group_url = coalesce(c.whatsapp_group_url, other.whatsapp_group_url),
    photo_url          = coalesce(c.photo_url, other.photo_url),
    note               = coalesce(c.note, other.note),
    -- A confirmation of either record is not thrown away.
    verification_status = case when other.verification_status = 'verified' then 'verified' else c.verification_status end,
    verified_at        = coalesce(c.verified_at, other.verified_at),
    verified_by        = coalesce(c.verified_by, other.verified_by),
    former_record_ids  = array(
      select distinct id from unnest(c.former_record_ids || other.former_record_ids || array[other.record_id]) as id
       where id is not null and id is distinct from c.record_id
       order by id)
  where c.id = p_keep;

  delete from public.churches where id = p_other;
end $$;

revoke all on function public.merge_church_into(uuid, uuid) from public, anon, authenticated;

-- ------------------------------------------------------------ importação --

create table if not exists public.data_imports (
  name       text primary key,
  applied_at timestamptz not null default now()
);
-- No policy: nobody reads it through the API.
alter table public.data_imports enable row level security;

create temp table directory_import (
  ord               serial,
  record_id         text not null,
  former_record_ids text[] not null,
  modality          text not null,
  seat              text,
  country_code      text,
  country           text,
  region            text,
  locality          text,
  address           text,
  leader_name       text,
  leader_phone      text,
  other_leaders     jsonb not null,
  source            text,
  services          jsonb not null
) on commit drop;

insert into directory_import (record_id, former_record_ids, modality, seat, country_code, country, region, locality,
                              address, leader_name, leader_phone, other_leaders, source, services) values
  ('ao-kifica', array['source_record_001', 'source_record_064']::text[], 'physical', 'mundial', 'AO', 'Angola', 'Luanda', 'Kifica', 'Rua 149, Bairro Kifica, Distrito do Benfica. Município de Talatona. Luanda,Angola.', 'Bp. Rufino Boaz', '+244 922 846 000', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-sede-bairro-da-fronteira', array['source_record_012', 'source_record_065']::text[], 'physical', null, 'AO', 'Angola', 'Benguela', 'Sede - Bairro da Fronteira', 'Bairro da Massangarala( No Ex. Salão de festa Ndayaka defronte à Escola Deolinda Rodrigues).', 'Bp. Rui Vaz', '+244 923 409 830', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "16:30", "label": null}, {"weekday": 6, "start_time": "09:30", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('ao-baia-farta-vila-da-baia', array['source_record_013', 'source_record_066']::text[], 'physical', null, 'AO', 'Angola', 'Benguela', 'Baía Farta - Vila da Baía', null, 'Pr. Marcelo Cassengue', '+244 928 854 199', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "16:30", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-cidade-baixa', array['source_record_014', 'source_record_067']::text[], 'physical', null, 'AO', 'Angola', 'Huambo', 'Cidade Baixa', 'Bairro Bomba Alta, defronte a primeira ponte que está antes do Bem Barato na via Cambiote.', 'Pr. Wilson Matuca', '+244 923 364 892', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-saurimo-sassamba', array['source_record_019', 'source_record_068']::text[], 'physical', null, 'AO', 'Angola', 'Lunda Sul', 'Saurimo - Sassamba', 'Bairro Sassamba, rua da vala (nas mediações dos Armazéns do Lucas)', 'Pr. Fábio Francisco', '+244 925 290 774', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-saurimo-candembe', array['source_record_020', 'source_record_069']::text[], 'physical', null, 'AO', 'Angola', 'Lunda Sul', 'Saurimo - Candembe', 'Bairro Candembe, rua das Muagens, nas mediações do complexo escolar Mahat Magand.', 'Pr. Aux. Bonifácio Muatxitambuila', '+244 937 547 161', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-cabassango', array['source_record_023', 'source_record_070']::text[], 'physical', null, 'AO', 'Angola', 'Cabinda', 'Cabassango', 'Bairro de Cabassango, por detrás da Praça.', 'Pr. Manuel Luemba', '+244 923 898 009', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-lubango-helder-neto', array['source_record_024', 'source_record_071']::text[], 'physical', null, 'AO', 'Angola', 'Huíla', 'Lubango - Hélder Neto', 'Bairro da Mitcha, depois da paragem do Paulo Dias, lado direito da estrada que vai a praça nova.', 'Pr. Sérgio Jamba', '+244 934 982 958', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "17:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:30", "label": null}]'::jsonb),
  ('ao-quibala-cambango', array['source_record_072']::text[], 'physical', null, 'AO', 'Angola', 'Cuanza Sul', 'Quibala - Cambango', null, 'Pr. António Avelar', '+244 925 619 540', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 6, "start_time": "15:00", "label": null}]'::jsonb),
  ('pt-pontinha', array['source_record_025', 'source_record_073']::text[], 'physical', 'nacional', 'PT', 'Portugal', 'Lisboa', 'Pontinha', 'Travessa Quinta das Arrombas 99, 1675-76 Serra da Luz - Pontinha', 'Bp. João Cardoso', '+351 929 259 327', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "19:00", "label": null}, {"weekday": 6, "start_time": "10:00", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('pt-caldas-da-rainha', array['source_record_027', 'source_record_074']::text[], 'physical', null, 'PT', 'Portugal', 'Leiria', 'Caldas da Rainha', 'Rua Fonte do Pinheiro nº62 R/C, 2500-203, Caldas da Rainha', 'Bp. Aux. Adriano Muginga', '+351 962 570 104', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 6, "start_time": "10:00", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('br-itatiba', array['source_record_075']::text[], 'physical', null, 'BR', 'Brasil', 'São Paulo', 'Itatiba', null, 'Pr. Sergio Sousa', '+55 11 99568 6057', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 6, "start_time": "19:00", "label": null}]'::jsonb),
  ('ao-estalagem', array['source_record_002']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Estalagem', 'Viana Estalagem, entrada do milénio junto ao Armazém do povo.', 'Bp. Panzo Bento', '+244 940 954 658', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-prenda', array['source_record_003']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Prenda', 'Bairro Prenda, por trás do Lote 22, na entrada da rua do Rescova (antiga rua da Grua).', 'Pr. Jaime José', '+244 924 152 734', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-cazenga-kalawenda', array['source_record_004']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Cazenga - Kalawenda', 'Rua Emissora, no Antigo Quintal do Amaral, próximo a Administração do Kalawenda.', 'Pr. Jonas Machado', '+244 945 110 016', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "17:00", "label": null}, {"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-sapu-2', array['source_record_005']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Sapú 2', null, 'Pr. Nicolau Elote', '+244 946 767 829', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "18:00", "label": null}, {"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]'::jsonb),
  ('ao-ramiros', array['source_record_006']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Ramiros', null, 'Pr. Kiteculo Samba', '+244 929 390 019', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "17:30", "label": null}, {"weekday": 4, "start_time": "17:30", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-mungo-benfica', array['source_record_016']::text[], 'physical', null, 'AO', 'Angola', 'Huambo', 'Mungo - Benfica', 'Bairro Miti, defronte a Globo Net.', 'Pr. Bento Menino', '+244 932 095 429', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-bailundo-espirito-santo', array['source_record_018']::text[], 'physical', null, 'AO', 'Angola', 'Huambo', 'Bailundo - Espírito Santo', null, 'Pr. Jesus Muandumba', '+244 938 351 523', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('ao-zango-1', array['source_record_021']::text[], 'physical', null, 'AO', 'Angola', 'Icolo e Bengo', 'Zango 1', null, 'Pr. Evandro Zacarias', '+244 940 626 015', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "17:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-caxito-quijoao', array['source_record_022']::text[], 'physical', null, 'AO', 'Angola', 'Bengo', 'Caxito - Quijoão', 'Rua do Centro de Saúde Abel dos Santos ao lado da Escola do Gê.', 'Pr. Francis', '+244 946 474 311', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-lualane', array['source_record_037']::text[], 'physical', 'nacional', 'MZ', 'Moçambique', null, 'Lualane', null, 'Bp. Osvaldo Chunga', '+258 842 486 394', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-cidade-de-tete', array['source_record_038']::text[], 'physical', null, 'MZ', 'Moçambique', 'Tete', 'Cidade de Tete', null, 'Bp. Aux. Edmo Carlos', '+258 84 034 8404', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "15:45", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]'::jsonb),
  ('mz-maxungue', array['source_record_039']::text[], 'physical', null, 'MZ', 'Moçambique', 'Maputo', 'Maxungue', null, 'Pr. Dumicilio Massangaie', '+258 87 741 8412', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-sangariveira', array['source_record_040']::text[], 'physical', null, 'MZ', 'Moçambique', 'Quelimane', 'Sangariveira', null, 'Pr. Hamurabe Alberto', '+258 84 028 7730', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "15:30", "label": null}, {"weekday": 0, "start_time": "08:30", "label": null}]'::jsonb),
  ('mz-pemba', array['source_record_041']::text[], 'physical', null, 'MZ', 'Moçambique', 'Cabo Delgado', 'Pemba', null, 'Pr. Jonito Cocerate', '+258 86 048 9618', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "16:30", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-cidade-de-chimoio', array['source_record_042']::text[], 'physical', null, 'MZ', 'Moçambique', 'Manica', 'Cidade de Chimoio', null, 'Pr. Antonio Jorge', '+258 87 001 9823', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "17:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-cidade-da-beira', array['source_record_043']::text[], 'physical', null, 'MZ', 'Moçambique', 'Sofala', 'Cidade da Beira', null, 'Pr. Samuel Carlitos', '+258 86 524 3471', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "17:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-maxixe', array['source_record_044']::text[], 'physical', null, 'MZ', 'Moçambique', 'Inhambane', 'Maxixe', null, 'Pr. Alício Nhabomba', '+258 84 154 0518', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-chongoene', array['source_record_045']::text[], 'physical', null, 'MZ', 'Moçambique', 'Gaza', 'Chongoene', null, 'Pr. Aux. Ismael Cossa', '+258 875 20 7044', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-cidade-de-nampula', array['source_record_046']::text[], 'physical', null, 'MZ', 'Moçambique', 'Nampula', 'Cidade de Nampula', null, 'Pr. Jackson D. Carlos', '+258 85 547 4154', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-cidade-de-lichinga', array['source_record_047']::text[], 'physical', null, 'MZ', 'Moçambique', 'Niassa', 'Cidade de Lichinga', null, 'Pr. Santos Felisberto', '+258 86 950 8009', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "17:30", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('mz-maxaquene', array['source_record_048']::text[], 'physical', null, 'MZ', 'Moçambique', 'Maputo Cidade', 'Maxaquene', null, 'Pr. Arnaldo Cossa', '+258 84 140 5824', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('pt-covilha', array['source_record_026']::text[], 'physical', null, 'PT', 'Portugal', 'Castelo Branco', 'Covilhã', null, 'Bp. Aux. Tony Nazireu', '+351 926 333 585', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 4, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('br-alto-garcas', array['source_record_051', 'source_record_052']::text[], 'physical', 'nacional', 'BR', 'Brasil', 'Mato Grosso', 'Alto Garças', null, 'Bp. Paulo Rodolfo', '+553 597 429106', '[{"name": "Pr. Adeilson", "phone": "+55 66 99637 5054"}]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]'::jsonb),
  ('br-sao-paulo-sede-estadual', array['source_record_053']::text[], 'physical', null, 'BR', 'Brasil', 'São Paulo', 'São Paulo - Sede Estadual', null, 'Bp. Aux. Juscelino', '+55 66 99632 7739', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('br-diadema', array['source_record_054']::text[], 'physical', null, 'BR', 'Brasil', 'São Paulo', 'Diadema', null, 'Bp. Aux. Gil Faustino', '+55 11 9861 07003', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('br-sao-domingos', array['source_record_060']::text[], 'physical', null, 'BR', 'Brasil', 'Maranhão', 'São Domingos', null, 'Pr. Joano', '+55 99 9935 0486', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]'::jsonb),
  ('br-terra-nova', array['source_record_058', 'source_record_063']::text[], 'physical', null, 'BR', 'Brasil', 'Bahia', 'Terra Nova', null, 'Pr. Israel Santos', '+55 71 9933 6908', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('br-altamira', array['source_record_057']::text[], 'physical', null, 'BR', 'Brasil', 'Pará', 'Altamira', null, 'Pr. Derinaldo', '+55 93 9 9217 1571', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]'::jsonb),
  ('br-santa-quiteria', array['source_record_056']::text[], 'physical', null, 'BR', 'Brasil', 'Ceará', 'Santa Quitéria', null, 'Pr. Fábio Henrique', '+55 86 99409 3956', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]'::jsonb),
  ('ao-morro-bento', array['source_record_008']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Morro Bento', 'Bairro do Morro Bento 1, Rua antes do banco Bic, junto a jonce, após ao consultório Daltonw .', 'Pr. Alberto Muacumbi', '+244 923 671 878', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "18:30", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-luanda-sul-viana', array['source_record_009']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Luanda Sul - Viana', null, 'Pr. Isumauro Sousa', '+244 949 119 465', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]'::jsonb),
  ('ao-camama', array['source_record_010']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Camama', null, 'Pr. Vasco Sahombo', '+244 937 630 285', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 3, "start_time": "18:30", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]'::jsonb),
  ('ao-calomanda', array['source_record_015']::text[], 'physical', null, 'AO', 'Angola', 'Huambo', 'Calomanda', 'Bairro da Calomanda, por detrás da IECA, ao lado da praça.', 'Pr. Valdir Sombreiro', '+244 939 097 678', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 2, "start_time": "16:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('online-estados-unidos-da-america', array['online_record_001']::text[], 'online', null, 'US', 'Estados Unidos da América', null, null, null, 'Bp. Rui Vaz', '+244 923 409 830', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-canada', array['online_record_002']::text[], 'online', null, 'CA', 'Canadá', null, null, null, 'Bp. Rui Vaz', '+244 923 409 830', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-africa-do-sul', array['online_record_003']::text[], 'online', null, 'ZA', 'África do Sul', null, null, null, 'Bp. Rufino Boaz', '+244 922 846 000', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-suica', array['online_record_004']::text[], 'online', null, 'CH', 'Suíça', null, null, null, 'Bp. Panzo Bento', '+244 940 954 658', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-noruega', array['online_record_005']::text[], 'online', null, 'NO', 'Noruega', null, null, null, 'Pr. Gaspar Clemente', '+47 906 64 958', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-congo', array['online_record_006']::text[], 'online', null, 'CD', 'Congo', null, null, null, 'Pr. Gaspar Clemente', '+47 906 64 958', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-tanzania', array['online_record_007']::text[], 'online', null, 'TZ', 'Tanzânia', null, null, null, 'Pr. Nilton Silva', '+244 929 184 966', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-quenia', array['online_record_008']::text[], 'online', null, 'KE', 'Quénia', null, null, null, 'Pr. Nilton Silva', '+244 929 184 966', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-senegal', array['online_record_009']::text[], 'online', null, 'SN', 'Senegal', null, null, null, 'Pr. José Chicussa', '+351 967 377 074', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('online-polonia', array['online_record_010']::text[], 'online', null, 'PL', 'Polónia', null, null, null, 'Pr. João Levi', '+48 579 385 641', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[]'::jsonb),
  ('br-vicentinopolis', array['source_record_055']::text[], 'physical', null, 'BR', 'Brasil', 'Goiás', 'Vicentinópolis', null, 'Pr. Júlio Cesár', '+55 64 99270 9408', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "19:30", "label": null}]'::jsonb),
  ('br-nova-lima', array['source_record_059']::text[], 'physical', null, 'BR', 'Brasil', 'Minas Gerais', 'Nova Lima', null, 'Pr. Igor Melo', '+55 31 8874 1010', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "19:00", "label": null}]'::jsonb),
  ('br-arraial-do-piaui', array['source_record_061']::text[], 'physical', null, 'BR', 'Brasil', 'Piauí', 'Arraial do Piauí', null, 'Pr. Aux. Nonato Ramos', '+55 89 9419 6907', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "19:00", "label": null}]'::jsonb),
  ('br-belo-horizonte', array['source_record_062']::text[], 'physical', null, 'BR', 'Brasil', 'Minas Gerais', 'Belo Horizonte', null, 'Bp. Aux. Gil Faustino', '+55 11 9 86107003', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "09:00", "label": null}]'::jsonb),
  ('pt-caranguejeira', array['source_record_028']::text[], 'physical', null, 'PT', 'Portugal', 'Leiria', 'Caranguejeira', null, 'Pr. Júlio Medeiros', '+351 963 091 506', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "18:00", "label": null}]'::jsonb),
  ('pt-porto', array['source_record_029']::text[], 'physical', null, 'PT', 'Portugal', null, 'Porto', null, 'Pr. Estevão Lourenço', '+351 919 200 255', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('pt-braga', array['source_record_030']::text[], 'physical', null, 'PT', 'Portugal', null, 'Braga', null, 'Pr. Júlio Domingos', '+351 936 239 861', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('de-wolfsburg', array['source_record_031']::text[], 'physical', 'nacional', 'DE', 'Alemanha', null, 'Wolfsburg', null, 'Bp. Rui Vaz', '+244 923 409 830', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": null, "label": "Via Zoom"}]'::jsonb),
  ('de-sankt-augustin', array['source_record_032']::text[], 'physical', null, 'DE', 'Alemanha', null, 'Sankt Augustin', null, 'Bp. Aux. Panzo Kizembe', '+491 5772 006 814', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "12:00", "label": null}]'::jsonb),
  ('de-bayern-de-munique', array['source_record_033']::text[], 'physical', null, 'DE', 'Alemanha', null, 'Bayern de Munique', null, 'Pr. Rodrigues Israel', '+491 5212 169 606', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "13:00", "label": null}]'::jsonb),
  ('gb-leeds', array['source_record_034']::text[], 'physical', 'nacional', 'GB', 'Inglaterra', null, 'Leeds', null, 'Bp. Aux. David Manuel', '+447 922 891 632', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "10:00", "label": null}]'::jsonb),
  ('gb-londres', array['source_record_035']::text[], 'physical', null, 'GB', 'Inglaterra', null, 'Londres', null, 'Pr. Edson Sabones', '+44 7701 338 327', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "13:00", "label": null}]'::jsonb),
  ('fr-paris', array['source_record_036']::text[], 'physical', 'nacional', 'FR', 'França', null, 'Paris', null, 'Bp. Manuel Francisco', '+33 613 941 436', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "12:30", "label": null}]'::jsonb),
  ('ao-cacuaco-cale', array['source_record_007']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Cacuaco - Calé', 'Bairro do Calé, na entrada do Novo Ginásio', 'Pr. Manuel Crucificado', '+244 935 160 662', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "07:00", "label": null}]'::jsonb),
  ('ao-golf-2', array['source_record_011']::text[], 'physical', null, 'AO', 'Angola', 'Luanda', 'Golf 2', null, 'Pr. António Baptista', '+244 928 522 121', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "08:00", "label": null}]'::jsonb),
  ('ao-mungo-aldeia-do-mbata', array['source_record_017']::text[], 'physical', null, 'AO', 'Angola', 'Huambo', 'Mungo - Aldeia do Mbata', null, 'Pr. Osvaldo Piedade', '+244 931 738 629', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": "15:00", "label": null}]'::jsonb),
  ('st-neves', array['source_record_049']::text[], 'physical', 'nacional', 'ST', 'São Tomé e Príncipe', null, 'Neves', null, 'Bp. José Medeiros', '+239 992 09 16', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": null, "label": null}]'::jsonb),
  ('st-capital', array['source_record_050']::text[], 'physical', null, 'ST', 'São Tomé e Príncipe', null, 'Capital', null, 'Bp. Aux. Dulcino da Veiga', '+239 993 23 36', '[]'::jsonb, 'Lista geral de cultos da equipa (setembro de 2026)', '[{"weekday": 0, "start_time": null, "label": null}]'::jsonb);

do $$
declare
  item  record;
  keep  uuid;
  other uuid;
begin
  if exists (select 1 from public.data_imports where name = '20260919160000_diretorio_lista_geral') then
    raise notice 'A importação 20260919160000_diretorio_lista_geral já foi aplicada: nada a fazer.';
    return;
  end if;

  -- The seats are given place by place below; none is left standing from
  -- before, so no country has two while that runs.
  update public.churches set seat = null where seat is not null;

  for item in select * from directory_import order by ord loop
    -- The record that becomes this place: the one with its new id, if a
    -- previous run created it, or else the first of the ids it had before.
    keep := null;
    select c.id into keep from public.churches c
     where c.record_id = item.record_id or c.record_id = any(item.former_record_ids)
     order by c.record_id = item.record_id desc, array_position(item.former_record_ids, c.record_id)
     limit 1;
    if keep is null then
      insert into public.churches (record_id, modality) values (item.record_id, item.modality)
      returning id into keep;
    end if;

    for other in select c.id from public.churches c
      where c.id <> keep and (c.record_id = item.record_id or c.record_id = any(item.former_record_ids))
    loop
      perform public.merge_church_into(keep, other);
    end loop;

    update public.churches c set
      former_record_ids = array(
        select distinct id from unnest(c.former_record_ids || item.former_record_ids || array[c.record_id]) as id
         where id is not null and id <> item.record_id
         order by id),
      record_id          = item.record_id,
      modality           = item.modality,
      seat               = item.seat,
      country_code       = item.country_code,
      country            = item.country,
      region             = item.region,
      locality           = item.locality,
      -- The list's address when it gives one; otherwise whatever the team wrote.
      address            = coalesce(item.address, c.address),
      leader_name        = item.leader_name,
      leader_phone       = item.leader_phone,
      other_leaders      = item.other_leaders,
      source             = item.source,
      -- Retired by migration 003; cleared so they can never stand in for the
      -- times below.
      service_day        = null,
      service_time_local = null
    where c.id = keep;

    delete from public.church_services where church_id = keep;
    insert into public.church_services (church_id, weekday, start_time, label)
    select keep, (service ->> 'weekday')::smallint, nullif(service ->> 'start_time', '')::time, nullif(service ->> 'label', '')
      from jsonb_array_elements(item.services) as service;
  end loop;

  insert into public.data_imports (name) values ('20260919160000_diretorio_lista_geral');
  raise notice 'Importação 20260919160000_diretorio_lista_geral: 73 lugares.';
end $$;

commit;
