-- 20260919160000_diretorio_lista_geral: the directory, from the team's general list of services.
--
-- Generated by scripts/import_churches.py, together with data/igrejas.json, so
-- the database and the app's own copy never disagree. Do not edit by hand:
-- change the workbook or the script and generate a new migration.
-- data/importacao-igrejas.md lists every decision taken on the way.
--
-- In one transaction:
--  1. each place gains its seat (world or national), the other people
--     responsible for it, and the ids it had before, so old links still open;
--  2. the records that were one place announced twice (Kifica on Saturday,
--     Kifica on Sunday) become one, and everything that pointed at the second
--     — servants, a local editor, a member's "A minha ISTN", announcements —
--     is moved onto the first before it goes;
--  3. every place takes the list's data, and its service times are replaced
--     by the list's.
--
-- It runs once. The import is recorded in data_imports, and running the file
-- again changes nothing: an edit made in the panel afterwards is never undone
-- by a second run.

begin;

-- ----------------------------------------------------------------- colunas --

alter table public.churches
  add column if not exists seat              text,
  add column if not exists other_leaders     jsonb  not null default '[]'::jsonb,
  add column if not exists former_record_ids text[] not null default '{}';

do $$ begin
  alter table public.churches
    add constraint churches_seat_known check (seat is null or seat in ('mundial', 'nacional'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.churches
    add constraint churches_other_leaders_list check (jsonb_typeof(other_leaders) = 'array');
exception when duplicate_object then null; end $$;

-- One world seat, and at most one national seat in each country.
create unique index if not exists churches_one_world_seat
  on public.churches ((seat)) where seat = 'mundial';
create unique index if not exists churches_one_national_seat
  on public.churches ((coalesce(country_code, country))) where seat = 'nacional';

create index if not exists churches_former_record_ids_idx
  on public.churches using gin (former_record_ids);

comment on column public.churches.seat is
  'mundial ou nacional. Só a equipa central muda, com set_church_seat.';
comment on column public.churches.other_leaders is
  'Outros responsáveis além de leader_name, [{name, phone}], como os anúncios os publicam.';
comment on column public.churches.former_record_ids is
  'Identificadores que este lugar teve antes, para que links e «A minha ISTN» antigos continuem a abri-lo.';

-- ------------------------------------------------------------------- sede --

-- The seat says something about the whole ISTN, not about one place, so a
-- local editor cannot give it to their own church, even through the API.
-- Without a signed-in user this is the SQL editor or a migration.
create or replace function public.protect_church_seat()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or public.is_central() then
    return new;
  end if;
  new.seat := old.seat;
  return new;
end $$;

drop trigger if exists churches_protect_seat on public.churches;
create trigger churches_protect_seat
  before update on public.churches
  for each row execute function public.protect_church_seat();

-- Giving a place a seat takes it from whoever held it, in the same
-- transaction: the unique indexes would otherwise refuse the second place
-- while the first still has it.
create or replace function public.set_church_seat(p_church uuid, p_seat text)
returns void language plpgsql security invoker set search_path = public as $$
declare
  target public.churches;
begin
  if not public.is_central() then
    raise exception 'Só a equipa central define as sedes.';
  end if;
  if p_seat is not null and p_seat not in ('mundial', 'nacional') then
    raise exception 'Sede desconhecida: %.', p_seat;
  end if;
  select * into target from public.churches where id = p_church;
  if not found then
    raise exception 'Igreja não encontrada.';
  end if;
  if p_seat = 'mundial' then
    update public.churches set seat = null where seat = 'mundial' and id <> p_church;
  elsif p_seat = 'nacional' then
    update public.churches set seat = null
     where seat = 'nacional' and id <> p_church
       and coalesce(country_code, country) = coalesce(target.country_code, target.country);
  end if;
  update public.churches set seat = p_seat where id = p_church;
end $$;

revoke all on function public.set_church_seat(uuid, text) from public, anon;
grant execute on function public.set_church_seat(uuid, text) to authenticated;

-- ---------------------------------------------------- juntar dois registos --

-- p_other is the same place as p_keep: everything that points at p_other
-- moves to p_keep, what the team filled in on p_other is kept where p_keep has
-- nothing, and p_other goes. Only the SQL editor can call it.
create or replace function public.merge_church_into(p_keep uuid, p_other uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  other public.churches;
begin
  if p_keep = p_other then
    return;
  end if;
  select * into other from public.churches where id = p_other;
  if not found then
    return;
  end if;

  update public.servos set church_id = p_keep where church_id = p_other;
  update public.admin_profiles set church_id = p_keep where church_id = p_other;
  update public.app_users set home_church_id = p_keep where home_church_id = p_other;
  -- posts.church_id cascades on delete: an announcement left pointing at
  -- p_other would disappear with it.
  update public.posts set church_id = p_keep where church_id = p_other;

  update public.churches c set
    place_type         = coalesce(c.place_type, other.place_type),
    became_church_on   = coalesce(c.became_church_on, other.became_church_on),
    address            = coalesce(c.address, other.address),
    whatsapp_group_url = coalesce(c.whatsapp_group_url, other.whatsapp_group_url),
    photo_url          = coalesce(c.photo_url, other.photo_url),
    note               = coalesce(c.note, other.note),
    -- A confirmation of either record is not thrown away.
    verification_status = case when other.verification_status = 'verified' then 'verified' else c.verification_status end,
    verified_at        = coalesce(c.verified_at, other.verified_at),
    verified_by        = coalesce(c.verified_by, other.verified_by),
    former_record_ids  = array(
      select distinct id from unnest(c.former_record_ids || other.former_record_ids || array[other.record_id]) as id
       where id is not null and id is distinct from c.record_id
       order by id)
  where c.id = p_keep;

  delete from public.churches where id = p_other;
end $$;

revoke all on function public.merge_church_into(uuid, uuid) from public, anon, authenticated;

-- ------------------------------------------------------------ importação --

create table if not exists public.data_imports (
  name       text primary key,
  applied_at timestamptz not null default now()
);
-- No policy: nobody reads it through the API.
alter table public.data_imports enable row level security;

-- The places travel inside this block, as one JSON document, and the whole
-- import is a single statement. A temporary table would be simpler to read,
-- but the Supabase SQL editor runs each statement of a file on its own, and a
-- temporary table does not survive that.
do $import$
declare
  item  record;
  keep  uuid;
  other uuid;
  places constant jsonb := $places$[
  {"record_id": "ao-kifica", "former_record_ids": ["source_record_001", "source_record_064"], "modality": "physical", "seat": "mundial", "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Kifica", "address": "Rua 149, Bairro Kifica, Distrito do Benfica. Município de Talatona. Luanda,Angola.", "leader_name": "Bp. Rufino Boaz", "leader_phone": "+244 922 846 000", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-sede-bairro-da-fronteira", "former_record_ids": ["source_record_012", "source_record_065"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Benguela", "locality": "Sede - Bairro da Fronteira", "address": "Bairro da Massangarala( No Ex. Salão de festa Ndayaka defronte à Escola Deolinda Rodrigues).", "leader_name": "Bp. Rui Vaz", "leader_phone": "+244 923 409 830", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "16:30", "label": null}, {"weekday": 6, "start_time": "09:30", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "ao-baia-farta-vila-da-baia", "former_record_ids": ["source_record_013", "source_record_066"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Benguela", "locality": "Baía Farta - Vila da Baía", "address": null, "leader_name": "Pr. Marcelo Cassengue", "leader_phone": "+244 928 854 199", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "16:30", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-cidade-baixa", "former_record_ids": ["source_record_014", "source_record_067"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Huambo", "locality": "Cidade Baixa", "address": "Bairro Bomba Alta, defronte a primeira ponte que está antes do Bem Barato na via Cambiote.", "leader_name": "Pr. Wilson Matuca", "leader_phone": "+244 923 364 892", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-saurimo-sassamba", "former_record_ids": ["source_record_019", "source_record_068"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Lunda Sul", "locality": "Saurimo - Sassamba", "address": "Bairro Sassamba, rua da vala (nas mediações dos Armazéns do Lucas)", "leader_name": "Pr. Fábio Francisco", "leader_phone": "+244 925 290 774", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-saurimo-candembe", "former_record_ids": ["source_record_020", "source_record_069"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Lunda Sul", "locality": "Saurimo - Candembe", "address": "Bairro Candembe, rua das Muagens, nas mediações do complexo escolar Mahat Magand.", "leader_name": "Pr. Aux. Bonifácio Muatxitambuila", "leader_phone": "+244 937 547 161", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-cabassango", "former_record_ids": ["source_record_023", "source_record_070"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Cabinda", "locality": "Cabassango", "address": "Bairro de Cabassango, por detrás da Praça.", "leader_name": "Pr. Manuel Luemba", "leader_phone": "+244 923 898 009", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-lubango-helder-neto", "former_record_ids": ["source_record_024", "source_record_071"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Huíla", "locality": "Lubango - Hélder Neto", "address": "Bairro da Mitcha, depois da paragem do Paulo Dias, lado direito da estrada que vai a praça nova.", "leader_name": "Pr. Sérgio Jamba", "leader_phone": "+244 934 982 958", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "17:00", "label": null}, {"weekday": 6, "start_time": "09:00", "label": null}, {"weekday": 0, "start_time": "09:30", "label": null}]},
  {"record_id": "ao-quibala-cambango", "former_record_ids": ["source_record_072"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Cuanza Sul", "locality": "Quibala - Cambango", "address": null, "leader_name": "Pr. António Avelar", "leader_phone": "+244 925 619 540", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 6, "start_time": "15:00", "label": null}]},
  {"record_id": "pt-pontinha", "former_record_ids": ["source_record_025", "source_record_073"], "modality": "physical", "seat": "nacional", "country_code": "PT", "country": "Portugal", "region": "Lisboa", "locality": "Pontinha", "address": "Travessa Quinta das Arrombas 99, 1675-76 Serra da Luz - Pontinha", "leader_name": "Bp. João Cardoso", "leader_phone": "+351 929 259 327", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "19:00", "label": null}, {"weekday": 6, "start_time": "10:00", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "pt-caldas-da-rainha", "former_record_ids": ["source_record_027", "source_record_074"], "modality": "physical", "seat": null, "country_code": "PT", "country": "Portugal", "region": "Leiria", "locality": "Caldas da Rainha", "address": "Rua Fonte do Pinheiro nº62 R/C, 2500-203, Caldas da Rainha", "leader_name": "Bp. Aux. Adriano Muginga", "leader_phone": "+351 962 570 104", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 6, "start_time": "10:00", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "br-itatiba", "former_record_ids": ["source_record_075"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "São Paulo", "locality": "Itatiba", "address": null, "leader_name": "Pr. Sergio Sousa", "leader_phone": "+55 11 99568 6057", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 6, "start_time": "19:00", "label": null}]},
  {"record_id": "ao-estalagem", "former_record_ids": ["source_record_002"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Estalagem", "address": "Viana Estalagem, entrada do milénio junto ao Armazém do povo.", "leader_name": "Bp. Panzo Bento", "leader_phone": "+244 940 954 658", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-prenda", "former_record_ids": ["source_record_003"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Prenda", "address": "Bairro Prenda, por trás do Lote 22, na entrada da rua do Rescova (antiga rua da Grua).", "leader_name": "Pr. Jaime José", "leader_phone": "+244 924 152 734", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-cazenga-kalawenda", "former_record_ids": ["source_record_004"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Cazenga - Kalawenda", "address": "Rua Emissora, no Antigo Quintal do Amaral, próximo a Administração do Kalawenda.", "leader_name": "Pr. Jonas Machado", "leader_phone": "+244 945 110 016", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "17:00", "label": null}, {"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-sapu-2", "former_record_ids": ["source_record_005"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Sapú 2", "address": null, "leader_name": "Pr. Nicolau Elote", "leader_phone": "+244 946 767 829", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "18:00", "label": null}, {"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]},
  {"record_id": "ao-ramiros", "former_record_ids": ["source_record_006"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Ramiros", "address": null, "leader_name": "Pr. Kiteculo Samba", "leader_phone": "+244 929 390 019", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "17:30", "label": null}, {"weekday": 4, "start_time": "17:30", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-mungo-benfica", "former_record_ids": ["source_record_016"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Huambo", "locality": "Mungo - Benfica", "address": "Bairro Miti, defronte a Globo Net.", "leader_name": "Pr. Bento Menino", "leader_phone": "+244 932 095 429", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-bailundo-espirito-santo", "former_record_ids": ["source_record_018"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Huambo", "locality": "Bailundo - Espírito Santo", "address": null, "leader_name": "Pr. Jesus Muandumba", "leader_phone": "+244 938 351 523", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "ao-zango-1", "former_record_ids": ["source_record_021"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Icolo e Bengo", "locality": "Zango 1", "address": null, "leader_name": "Pr. Evandro Zacarias", "leader_phone": "+244 940 626 015", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "17:00", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-caxito-quijoao", "former_record_ids": ["source_record_022"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Bengo", "locality": "Caxito - Quijoão", "address": "Rua do Centro de Saúde Abel dos Santos ao lado da Escola do Gê.", "leader_name": "Pr. Francis", "leader_phone": "+244 946 474 311", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "15:00", "label": null}, {"weekday": 4, "start_time": "15:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-lualane", "former_record_ids": ["source_record_037"], "modality": "physical", "seat": "nacional", "country_code": "MZ", "country": "Moçambique", "region": null, "locality": "Lualane", "address": null, "leader_name": "Bp. Osvaldo Chunga", "leader_phone": "+258 842 486 394", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-cidade-de-tete", "former_record_ids": ["source_record_038"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Tete", "locality": "Cidade de Tete", "address": null, "leader_name": "Bp. Aux. Edmo Carlos", "leader_phone": "+258 84 034 8404", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "15:45", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]},
  {"record_id": "mz-maxungue", "former_record_ids": ["source_record_039"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Maputo", "locality": "Maxungue", "address": null, "leader_name": "Pr. Dumicilio Massangaie", "leader_phone": "+258 87 741 8412", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-sangariveira", "former_record_ids": ["source_record_040"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Quelimane", "locality": "Sangariveira", "address": null, "leader_name": "Pr. Hamurabe Alberto", "leader_phone": "+258 84 028 7730", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "15:30", "label": null}, {"weekday": 0, "start_time": "08:30", "label": null}]},
  {"record_id": "mz-pemba", "former_record_ids": ["source_record_041"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Cabo Delgado", "locality": "Pemba", "address": null, "leader_name": "Pr. Jonito Cocerate", "leader_phone": "+258 86 048 9618", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "16:30", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-cidade-de-chimoio", "former_record_ids": ["source_record_042"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Manica", "locality": "Cidade de Chimoio", "address": null, "leader_name": "Pr. Antonio Jorge", "leader_phone": "+258 87 001 9823", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "17:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-cidade-da-beira", "former_record_ids": ["source_record_043"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Sofala", "locality": "Cidade da Beira", "address": null, "leader_name": "Pr. Samuel Carlitos", "leader_phone": "+258 86 524 3471", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "17:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-maxixe", "former_record_ids": ["source_record_044"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Inhambane", "locality": "Maxixe", "address": null, "leader_name": "Pr. Alício Nhabomba", "leader_phone": "+258 84 154 0518", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-chongoene", "former_record_ids": ["source_record_045"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Gaza", "locality": "Chongoene", "address": null, "leader_name": "Pr. Aux. Ismael Cossa", "leader_phone": "+258 875 20 7044", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-cidade-de-nampula", "former_record_ids": ["source_record_046"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Nampula", "locality": "Cidade de Nampula", "address": null, "leader_name": "Pr. Jackson D. Carlos", "leader_phone": "+258 85 547 4154", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "16:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-cidade-de-lichinga", "former_record_ids": ["source_record_047"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Niassa", "locality": "Cidade de Lichinga", "address": null, "leader_name": "Pr. Santos Felisberto", "leader_phone": "+258 86 950 8009", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "17:30", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "mz-maxaquene", "former_record_ids": ["source_record_048"], "modality": "physical", "seat": null, "country_code": "MZ", "country": "Moçambique", "region": "Maputo Cidade", "locality": "Maxaquene", "address": null, "leader_name": "Pr. Arnaldo Cossa", "leader_phone": "+258 84 140 5824", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "pt-covilha", "former_record_ids": ["source_record_026"], "modality": "physical", "seat": null, "country_code": "PT", "country": "Portugal", "region": "Castelo Branco", "locality": "Covilhã", "address": null, "leader_name": "Bp. Aux. Tony Nazireu", "leader_phone": "+351 926 333 585", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 4, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "br-alto-garcas", "former_record_ids": ["source_record_051", "source_record_052"], "modality": "physical", "seat": "nacional", "country_code": "BR", "country": "Brasil", "region": "Mato Grosso", "locality": "Alto Garças", "address": null, "leader_name": "Bp. Paulo Rodolfo", "leader_phone": "+553 597 429106", "other_leaders": [{"name": "Pr. Adeilson", "phone": "+55 66 99637 5054"}], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]},
  {"record_id": "br-sao-paulo-sede-estadual", "former_record_ids": ["source_record_053"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "São Paulo", "locality": "São Paulo - Sede Estadual", "address": null, "leader_name": "Bp. Aux. Juscelino", "leader_phone": "+55 66 99632 7739", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "br-diadema", "former_record_ids": ["source_record_054"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "São Paulo", "locality": "Diadema", "address": null, "leader_name": "Bp. Aux. Gil Faustino", "leader_phone": "+55 11 9861 07003", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "br-sao-domingos", "former_record_ids": ["source_record_060"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Maranhão", "locality": "São Domingos", "address": null, "leader_name": "Pr. Joano", "leader_phone": "+55 99 9935 0486", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]},
  {"record_id": "br-terra-nova", "former_record_ids": ["source_record_058", "source_record_063"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Bahia", "locality": "Terra Nova", "address": null, "leader_name": "Pr. Israel Santos", "leader_phone": "+55 71 9933 6908", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "br-altamira", "former_record_ids": ["source_record_057"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Pará", "locality": "Altamira", "address": null, "leader_name": "Pr. Derinaldo", "leader_phone": "+55 93 9 9217 1571", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]},
  {"record_id": "br-santa-quiteria", "former_record_ids": ["source_record_056"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Ceará", "locality": "Santa Quitéria", "address": null, "leader_name": "Pr. Fábio Henrique", "leader_phone": "+55 86 99409 3956", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "19:00", "label": null}, {"weekday": 0, "start_time": "19:00", "label": null}]},
  {"record_id": "ao-morro-bento", "former_record_ids": ["source_record_008"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Morro Bento", "address": "Bairro do Morro Bento 1, Rua antes do banco Bic, junto a jonce, após ao consultório Daltonw .", "leader_name": "Pr. Alberto Muacumbi", "leader_phone": "+244 923 671 878", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "18:30", "label": null}, {"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-luanda-sul-viana", "former_record_ids": ["source_record_009"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Luanda Sul - Viana", "address": null, "leader_name": "Pr. Isumauro Sousa", "leader_phone": "+244 949 119 465", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "18:00", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]},
  {"record_id": "ao-camama", "former_record_ids": ["source_record_010"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Camama", "address": null, "leader_name": "Pr. Vasco Sahombo", "leader_phone": "+244 937 630 285", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 3, "start_time": "18:30", "label": null}, {"weekday": 0, "start_time": "08:00", "label": null}]},
  {"record_id": "ao-calomanda", "former_record_ids": ["source_record_015"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Huambo", "locality": "Calomanda", "address": "Bairro da Calomanda, por detrás da IECA, ao lado da praça.", "leader_name": "Pr. Valdir Sombreiro", "leader_phone": "+244 939 097 678", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 2, "start_time": "16:00", "label": null}, {"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "online-estados-unidos-da-america", "former_record_ids": ["online_record_001"], "modality": "online", "seat": null, "country_code": "US", "country": "Estados Unidos da América", "region": null, "locality": null, "address": null, "leader_name": "Bp. Rui Vaz", "leader_phone": "+244 923 409 830", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-canada", "former_record_ids": ["online_record_002"], "modality": "online", "seat": null, "country_code": "CA", "country": "Canadá", "region": null, "locality": null, "address": null, "leader_name": "Bp. Rui Vaz", "leader_phone": "+244 923 409 830", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-africa-do-sul", "former_record_ids": ["online_record_003"], "modality": "online", "seat": null, "country_code": "ZA", "country": "África do Sul", "region": null, "locality": null, "address": null, "leader_name": "Bp. Rufino Boaz", "leader_phone": "+244 922 846 000", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-suica", "former_record_ids": ["online_record_004"], "modality": "online", "seat": null, "country_code": "CH", "country": "Suíça", "region": null, "locality": null, "address": null, "leader_name": "Bp. Panzo Bento", "leader_phone": "+244 940 954 658", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-noruega", "former_record_ids": ["online_record_005"], "modality": "online", "seat": null, "country_code": "NO", "country": "Noruega", "region": null, "locality": null, "address": null, "leader_name": "Pr. Gaspar Clemente", "leader_phone": "+47 906 64 958", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-congo", "former_record_ids": ["online_record_006"], "modality": "online", "seat": null, "country_code": "CD", "country": "Congo", "region": null, "locality": null, "address": null, "leader_name": "Pr. Gaspar Clemente", "leader_phone": "+47 906 64 958", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-tanzania", "former_record_ids": ["online_record_007"], "modality": "online", "seat": null, "country_code": "TZ", "country": "Tanzânia", "region": null, "locality": null, "address": null, "leader_name": "Pr. Nilton Silva", "leader_phone": "+244 929 184 966", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-quenia", "former_record_ids": ["online_record_008"], "modality": "online", "seat": null, "country_code": "KE", "country": "Quénia", "region": null, "locality": null, "address": null, "leader_name": "Pr. Nilton Silva", "leader_phone": "+244 929 184 966", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-senegal", "former_record_ids": ["online_record_009"], "modality": "online", "seat": null, "country_code": "SN", "country": "Senegal", "region": null, "locality": null, "address": null, "leader_name": "Pr. José Chicussa", "leader_phone": "+351 967 377 074", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "online-polonia", "former_record_ids": ["online_record_010"], "modality": "online", "seat": null, "country_code": "PL", "country": "Polónia", "region": null, "locality": null, "address": null, "leader_name": "Pr. João Levi", "leader_phone": "+48 579 385 641", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": []},
  {"record_id": "br-vicentinopolis", "former_record_ids": ["source_record_055"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Goiás", "locality": "Vicentinópolis", "address": null, "leader_name": "Pr. Júlio Cesár", "leader_phone": "+55 64 99270 9408", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "19:30", "label": null}]},
  {"record_id": "br-nova-lima", "former_record_ids": ["source_record_059"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Minas Gerais", "locality": "Nova Lima", "address": null, "leader_name": "Pr. Igor Melo", "leader_phone": "+55 31 8874 1010", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "19:00", "label": null}]},
  {"record_id": "br-arraial-do-piaui", "former_record_ids": ["source_record_061"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Piauí", "locality": "Arraial do Piauí", "address": null, "leader_name": "Pr. Aux. Nonato Ramos", "leader_phone": "+55 89 9419 6907", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "19:00", "label": null}]},
  {"record_id": "br-belo-horizonte", "former_record_ids": ["source_record_062"], "modality": "physical", "seat": null, "country_code": "BR", "country": "Brasil", "region": "Minas Gerais", "locality": "Belo Horizonte", "address": null, "leader_name": "Bp. Aux. Gil Faustino", "leader_phone": "+55 11 9 86107003", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "09:00", "label": null}]},
  {"record_id": "pt-caranguejeira", "former_record_ids": ["source_record_028"], "modality": "physical", "seat": null, "country_code": "PT", "country": "Portugal", "region": "Leiria", "locality": "Caranguejeira", "address": null, "leader_name": "Pr. Júlio Medeiros", "leader_phone": "+351 963 091 506", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "18:00", "label": null}]},
  {"record_id": "pt-porto", "former_record_ids": ["source_record_029"], "modality": "physical", "seat": null, "country_code": "PT", "country": "Portugal", "region": null, "locality": "Porto", "address": null, "leader_name": "Pr. Estevão Lourenço", "leader_phone": "+351 919 200 255", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "pt-braga", "former_record_ids": ["source_record_030"], "modality": "physical", "seat": null, "country_code": "PT", "country": "Portugal", "region": null, "locality": "Braga", "address": null, "leader_name": "Pr. Júlio Domingos", "leader_phone": "+351 936 239 861", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "de-wolfsburg", "former_record_ids": ["source_record_031"], "modality": "physical", "seat": "nacional", "country_code": "DE", "country": "Alemanha", "region": null, "locality": "Wolfsburg", "address": null, "leader_name": "Bp. Rui Vaz", "leader_phone": "+244 923 409 830", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": null, "label": "Via Zoom"}]},
  {"record_id": "de-sankt-augustin", "former_record_ids": ["source_record_032"], "modality": "physical", "seat": null, "country_code": "DE", "country": "Alemanha", "region": null, "locality": "Sankt Augustin", "address": null, "leader_name": "Bp. Aux. Panzo Kizembe", "leader_phone": "+491 5772 006 814", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "12:00", "label": null}]},
  {"record_id": "de-bayern-de-munique", "former_record_ids": ["source_record_033"], "modality": "physical", "seat": null, "country_code": "DE", "country": "Alemanha", "region": null, "locality": "Bayern de Munique", "address": null, "leader_name": "Pr. Rodrigues Israel", "leader_phone": "+491 5212 169 606", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "13:00", "label": null}]},
  {"record_id": "gb-leeds", "former_record_ids": ["source_record_034"], "modality": "physical", "seat": "nacional", "country_code": "GB", "country": "Inglaterra", "region": null, "locality": "Leeds", "address": null, "leader_name": "Bp. Aux. David Manuel", "leader_phone": "+447 922 891 632", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "10:00", "label": null}]},
  {"record_id": "gb-londres", "former_record_ids": ["source_record_035"], "modality": "physical", "seat": null, "country_code": "GB", "country": "Inglaterra", "region": null, "locality": "Londres", "address": null, "leader_name": "Pr. Edson Sabones", "leader_phone": "+44 7701 338 327", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "13:00", "label": null}]},
  {"record_id": "fr-paris", "former_record_ids": ["source_record_036"], "modality": "physical", "seat": "nacional", "country_code": "FR", "country": "França", "region": null, "locality": "Paris", "address": null, "leader_name": "Bp. Manuel Francisco", "leader_phone": "+33 613 941 436", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "12:30", "label": null}]},
  {"record_id": "ao-cacuaco-cale", "former_record_ids": ["source_record_007"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Cacuaco - Calé", "address": "Bairro do Calé, na entrada do Novo Ginásio", "leader_name": "Pr. Manuel Crucificado", "leader_phone": "+244 935 160 662", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "07:00", "label": null}]},
  {"record_id": "ao-golf-2", "former_record_ids": ["source_record_011"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Luanda", "locality": "Golf 2", "address": null, "leader_name": "Pr. António Baptista", "leader_phone": "+244 928 522 121", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "08:00", "label": null}]},
  {"record_id": "ao-mungo-aldeia-do-mbata", "former_record_ids": ["source_record_017"], "modality": "physical", "seat": null, "country_code": "AO", "country": "Angola", "region": "Huambo", "locality": "Mungo - Aldeia do Mbata", "address": null, "leader_name": "Pr. Osvaldo Piedade", "leader_phone": "+244 931 738 629", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": "15:00", "label": null}]},
  {"record_id": "st-neves", "former_record_ids": ["source_record_049"], "modality": "physical", "seat": "nacional", "country_code": "ST", "country": "São Tomé e Príncipe", "region": null, "locality": "Neves", "address": null, "leader_name": "Bp. José Medeiros", "leader_phone": "+239 992 09 16", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": null, "label": null}]},
  {"record_id": "st-capital", "former_record_ids": ["source_record_050"], "modality": "physical", "seat": null, "country_code": "ST", "country": "São Tomé e Príncipe", "region": null, "locality": "Capital", "address": null, "leader_name": "Bp. Aux. Dulcino da Veiga", "leader_phone": "+239 993 23 36", "other_leaders": [], "source": "Lista geral de cultos da equipa (setembro de 2026)", "services": [{"weekday": 0, "start_time": null, "label": null}]}
]$places$::jsonb;
begin
  if exists (select 1 from public.data_imports where name = '20260919160000_diretorio_lista_geral') then
    raise notice 'A importação 20260919160000_diretorio_lista_geral já foi aplicada: nada a fazer.';
    return;
  end if;

  -- The seats are given place by place below; none is left standing from
  -- before, so no country has two while that runs.
  update public.churches set seat = null where seat is not null;

  for item in
    select place.*
      from jsonb_array_elements(places) with ordinality as listed(value, ord)
      cross join lateral jsonb_to_record(listed.value) as place(
        record_id text, former_record_ids text[], modality text, seat text, country_code text, country text,
        region text, locality text, address text, leader_name text, leader_phone text, other_leaders jsonb,
        source text, services jsonb)
     order by listed.ord
  loop
    -- The record that becomes this place: the one with its new id, if a
    -- previous run created it, or else the first of the ids it had before.
    keep := null;
    select c.id into keep from public.churches c
     where c.record_id = item.record_id or c.record_id = any(item.former_record_ids)
     order by c.record_id = item.record_id desc, array_position(item.former_record_ids, c.record_id)
     limit 1;
    if keep is null then
      insert into public.churches (record_id, modality) values (item.record_id, item.modality)
      returning id into keep;
    end if;

    for other in select c.id from public.churches c
      where c.id <> keep and (c.record_id = item.record_id or c.record_id = any(item.former_record_ids))
    loop
      perform public.merge_church_into(keep, other);
    end loop;

    update public.churches c set
      former_record_ids = array(
        select distinct id from unnest(c.former_record_ids || item.former_record_ids || array[c.record_id]) as id
         where id is not null and id <> item.record_id
         order by id),
      record_id          = item.record_id,
      modality           = item.modality,
      seat               = item.seat,
      country_code       = item.country_code,
      country            = item.country,
      region             = item.region,
      locality           = item.locality,
      -- The list's address when it gives one; otherwise whatever the team wrote.
      address            = coalesce(item.address, c.address),
      leader_name        = item.leader_name,
      leader_phone       = item.leader_phone,
      other_leaders      = item.other_leaders,
      source             = item.source,
      -- Retired by migration 003; cleared so they can never stand in for the
      -- times below.
      service_day        = null,
      service_time_local = null
    where c.id = keep;

    delete from public.church_services where church_id = keep;
    insert into public.church_services (church_id, weekday, start_time, label)
    select keep, (service ->> 'weekday')::smallint, nullif(service ->> 'start_time', '')::time, nullif(service ->> 'label', '')
      from jsonb_array_elements(item.services) as service;
  end loop;

  insert into public.data_imports (name) values ('20260919160000_diretorio_lista_geral');
  raise notice 'Importação 20260919160000_diretorio_lista_geral: 73 lugares.';
end $import$;

commit;
